"""oops forgor lol

Revision ID: 9d4e2a174c77
Revises: e048ee743462
Create Date: 2025-10-19 21:04:33.103073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4e2a174c77'
down_revision = 'e048ee743462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_branch_id'))
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.INTEGER(), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_branch_id'), ['branch_id'], unique=False)

    # ### end Alembic commands ###
